#!/usr/bin/env node
"use strict"

function printIntro() {
	console.log("\n\n\n--- Wage is a wannabe Game Engine. ---");
	console.log("written by Marco Stagni, thanks MrDoob.");
	console.log("----- < http://marcostagni.com > -----\n\n\n");
}

function printUsage() {
	console.log("USAGE: wage create <projectName>".blue);
	console.log("USAGE: wage serve <port>".blue);
}

var builder = require("./builder.js"),
	server = require('./simplehttpserver.js'),
	colors = require('colors');

if (process.argv.length > 2) {
	printIntro();
	var command = process.argv[2];
	if (command == "create") {
		var location = process.argv[3];
		if (location) {
			builder.create(location)
		} else {
			console.log('Please provide a location for the project'.red);
			printUsage();
		}
	} else if (command == 'serve') {
		var port = process.argv[3] ? process.argv[3] : 8000;
		server.start(port);
	} else{
		console.log("Sorry, only create and serve methods avaible right now.".red);
		printUsage();
	}
} else {
	printUsage();
}
