export const SAVE_STARTED = 'SAVE_STARTED';
export const SAVE_COMPLETED = 'SAVE_COMPLETED';
export const SAVE_ERROR = 'SAVE_ERROR';

export const LOAD_STARTED = 'LOAD_STARTED';
export const LOAD_COMPLETED= 'LOAD_COMPLETED';
export const LOAD_ERROR = 'LOAD_ERROR';

export const KEYBOARD_ENABLED = 'KEYBOARD_ENABLED';
export const MOUSE_ENABLED = 'MOUSE_ENABLED';
export const GAMEPAD_ENABLED = 'GAMEPAD_ENABLED';
export const INPUT_ENABLED = 'INPUT_ENABLED';

export const KEYBOARD_DISABLED = 'KEYBOARD_DISABLED';
export const MOUSE_DISABLED = 'MOUSE_DISABLED';
export const GAMEPAD_DISABLED = 'GAMEPAD_DISABLED';
export const INPUT_DISABLED = 'INPUT_DISABLED';

export const GAMEPAD_CONNECTED = 'GAMEPAD_CONNECTED';
export const GAMEPAD_DISCONNECTED = 'GAMEPAD_DISCONNECTED';

export const NETWORK_CHANGED = 'NETWORK_CHANGED';

export const UI_LOADING_SCREEN = 'UI_LOADING_SCREEN';

export const LOCATION_PATH_CHANGE = 'LOCATION_PATH_CHANGE';

export const RESET = 'RESET';
