export const ENTITY_TYPES = {
    SCENE: {
        TYPE: "SCENE",
        SUBTYPES: {
            DEFAULT: "SCENE.SUBTYPE.DEFAULT",
        },
    },
    CAMERA: {
        TYPE: "CAMERA",
        SUBTYPES: {
            DEFAULT: "CAMERA.SUBTYPE.DEFAULT",
            MAIN: "CAMERA.SUBTYPE.MAIN",
        },
    },
    MESH: {
        TYPE: "MESH.TYPE",
        SUBTYPES: {
            DEFAULT: "MESH.SUBTYPE.DEFAULT",
            BOX: "MESH.SUBTYPE.BOX",
            SPHERE: "MESH.SUBTYPE.SPHERE",
            PLANE: "MESH.SUBTYPE.PLANE",
            CYLINDER: "MESH.SUBTYPE.CYLINDER",
            CONE: "MESH.SUBTYPE.CONE",
            CUBE: "MESH.SUBTYPE.CUBE",
            LINE: "MESH.SUBTYPE.LINE",
            CURVE_LINE: "MESH.SUBTYPE.CURVE_LINE",
            AXES: "MESH.SUBTYPE.AXES",
            GRID: "MESH.SUBTYPE.GRID",
            TARGET: "MESH.SUBTYPE.TARGET",
        },
    },
    LABEL: {
        TYPE: "LABEL",
        SUBTYPES: {
            DEFAULT: "LABEL.SUBTYPE.DEFAULT",
        },
    },
    LIGHT: {
        TYPE: "LIGHT.TYPE",
        SUBTYPES: {
            DEFAULT: "LIGHT.SUBTYPE.DEFAULT",
            AMBIENT: "LIGHT.SUBTYPE.AMBIENT",
            SUN: "LIGHT.SUBTYPE.SUN",
            HEMISPHERE: "LIGHT.SUBTYPE.HEMISPHERE",
            POINT: "LIGHT.SUBTYPE.POINT",
            SPOT: "LIGHT.SUBTYPE.SPOT",
        },
    },
    AUDIO: {
        TYPE: "AUDIO.TYPE",
        SUBTYPES: {
            DEFAULT: "AUDIO.SUBTYPE.DEFAULT",
            DIRECTIONAL: "AUDIO.SUBTYPE.DIRECTIONAL",
            AMBIENT: "AUDIO.SUBTYPE.AMBIENT",
        },
    },
    MODEL: {
        TYPE: "MODEL",
        SUBTYPES: {
            DEFAULT: "MODEL.SUBTYPE.DEFAULT",
        },
    },
    SPRITE: {
        TYPE: "SPRITE.TYPE",
        SUBTYPES: {
            DEFAULT: "SPRITE.SUBTYPE.DEFAULT",
            ANIMATED_SPRITE: "SPRITE.SUBTYPE.ANIMATED_SPRITE",
        },
    },
    PARTICLE: {
        TYPE: "PARTICLE",
        SUBTYPES: {
            DEFAULT: "PARTICLE.SUBTYPE.DEFAULT",
            EMITTER: "PARTICLE.SUBTYPE.EMITTER",
            SYSTEM: "PARTICLE.SUBTYPE.SYSTEM",
            EMITTER_GROUP: "PARTICLE.SUBTYPE.EMITTER_GROUP",
            PROTON_EMITTER: "PARTICLE.SUBTYPE.PROTON_EMITTER",
            EXPLOSION: "PARTICLE.SUBTYPE.EXPLOSION",
            FIRE: "PARTICLE.SUBTYPE.FIRE",
            FOUNTAIN: "PARTICLE.SUBTYPE.FOUNTAIN",
            RAIN: "PARTICLE.SUBTYPE.RAIN",
            SNOW: "PARTICLE.SUBTYPE.SNOW",
            TRAIL: "PARTICLE.SUBTYPE.TRAIL",
        },
    },
    SCENERY: {
        TYPE: "SCENERY",
        SUBTYPES: {
            DEFAULT: "SCENERY.SUBTYPE.DEFAULT",
            SKY: "SCENERY.SUBTYPE.SKY",
            SKYBOX: "SCENERY.SUBTYPE.SKYBOX",
        },
    },
    HELPER: {
        TYPE: "HELPER.TYPE",
        SUBTYPES: {
            GRID: "HELPER.SUBTYPE.GRID",
            AXES: "HELPER.SUBTYPE.AXES",
            HELPER_SPRITE: "HELPER.SUBTYPE.HELPER_SPRITE",
        },
        // GRID: "HELPER.GRID",
        // AXES: "HELPER.AXES",
    },
    UNKNOWN: "UNKNOWN",
};

export const FLAT_ENTITY_TYPES = [
    ENTITY_TYPES.SCENE.TYPE,
    ENTITY_TYPES.CAMERA.TYPE,
    ENTITY_TYPES.MESH.TYPE,
    ENTITY_TYPES.LABEL.TYPE,
    ENTITY_TYPES.LIGHT.TYPE,
    ENTITY_TYPES.AUDIO.TYPE,
    ENTITY_TYPES.MODEL.TYPE,
    ENTITY_TYPES.SPRITE.TYPE,
    ENTITY_TYPES.PARTICLE.TYPE,
    ENTITY_TYPES.SCENERY.TYPE,
    ENTITY_TYPES.HELPER.TYPE,
    ENTITY_TYPES.UNKNOWN,
];

export const FLAT_ENTITY_SUBTYPES = [
    ENTITY_TYPES.SCENE.SUBTYPES.DEFAULT,
    ENTITY_TYPES.CAMERA.SUBTYPES.DEFAULT,
    ENTITY_TYPES.CAMERA.SUBTYPES.MAIN,
    ENTITY_TYPES.MESH.SUBTYPES.DEFAULT,
    ENTITY_TYPES.MESH.SUBTYPES.BOX,
    ENTITY_TYPES.MESH.SUBTYPES.SPHERE,
    ENTITY_TYPES.MESH.SUBTYPES.PLANE,
    ENTITY_TYPES.MESH.SUBTYPES.CYLINDER,
    ENTITY_TYPES.MESH.SUBTYPES.CONE,
    ENTITY_TYPES.MESH.SUBTYPES.CUBE,
    ENTITY_TYPES.MESH.SUBTYPES.LINE,
    ENTITY_TYPES.MESH.SUBTYPES.CURVE_LINE,
    ENTITY_TYPES.MESH.SUBTYPES.AXES,
    ENTITY_TYPES.MESH.SUBTYPES.GRID,
    ENTITY_TYPES.MESH.SUBTYPES.TARGET,
    ENTITY_TYPES.LABEL.SUBTYPES.DEFAULT,
    ENTITY_TYPES.LIGHT.SUBTYPES.DEFAULT,
    ENTITY_TYPES.LIGHT.SUBTYPES.AMBIENT,
    ENTITY_TYPES.LIGHT.SUBTYPES.SUN,
    ENTITY_TYPES.LIGHT.SUBTYPES.HEMISPHERE,
    ENTITY_TYPES.LIGHT.SUBTYPES.POINT,
    ENTITY_TYPES.LIGHT.SUBTYPES.SPOT,
    ENTITY_TYPES.AUDIO.SUBTYPES.DEFAULT,
    ENTITY_TYPES.AUDIO.SUBTYPES.DIRECTIONAL,
    ENTITY_TYPES.AUDIO.SUBTYPES.AMBIENT,
    ENTITY_TYPES.MODEL.SUBTYPES.DEFAULT,
    ENTITY_TYPES.SPRITE.SUBTYPES.DEFAULT,
    ENTITY_TYPES.SPRITE.SUBTYPES.ANIMATED_SPRITE,
    ENTITY_TYPES.PARTICLE.SUBTYPES.DEFAULT,
    ENTITY_TYPES.PARTICLE.SUBTYPES.EMITTER,
    ENTITY_TYPES.PARTICLE.SUBTYPES.SYSTEM,
    ENTITY_TYPES.PARTICLE.SUBTYPES.EMITTER_GROUP,
    ENTITY_TYPES.PARTICLE.SUBTYPES.PROTON_EMITTER,
    ENTITY_TYPES.SCENERY.SUBTYPES.DEFAULT,
    ENTITY_TYPES.SCENERY.SUBTYPES.SKY,
    ENTITY_TYPES.SCENERY.SUBTYPES.SKYBOX,
    ENTITY_TYPES.HELPER.SUBTYPES.GRID,
    ENTITY_TYPES.HELPER.SUBTYPES.AXES,
    ENTITY_TYPES.HELPER.SUBTYPES.HELPER_SPRITE,
];

export const ENTITY_EVENTS = {
    DISPOSE: "DISPOSE",
    STATE_MACHINE: {
        CHANGE: "STATE_MACHINE_CHANGE",
    },
    ANIMATION: {
        LOOP: "LOOP",
        FINISHED: "FINISHED",
    },
    AUDIO: {
        ENDED: "ended",
    },
};

export const DEFAULT_TAG = "all";
