export const OFFSCREEN_CREATE = 'OFFSCREEN_CREATE';
export const OFFSCREEN_DISPOSE = 'OFFSCREEN_DISPOSE';
export const OFFSCREEN_INIT = 'OFFSCREEN_INIT';

export const OFFSCREEN_UPDATE_POSITION = 'OFFSCREEN_UPDATE_POSITION';
export const OFFSCREEN_UPDATE_ROTATION = 'OFFSCREEN_UPDATE_ROTATION';
export const OFFSCREEN_UPDATE_CAMERA_POSITION = 'OFFSCREEN_UPDATE_CAMERA_POSITION';
export const OFFSCREEN_UPDATE_CAMERA_ROTATION = 'OFFSCREEN_UPDATE_CAMERA_ROTATION';
export const OFFSCREEN_RESIZE_EVENT = 'OFFSCREEN_RESIZE';
export const OFFSCREEN_AUDIO_LISTENER_UPDATE_EVENT = 'OFFSCREEN_AUDIO_LISTENER_UPDATE_EVENT';
export const OFFSCREEN_PROXYCAMERA_UPDATE_EVENT = 'OFFSCREEN_PROXYCAMERA_UPDATE_EVENT';

export const OFFSCREEN_SET_CLEARCOLOR = 'OFFSCREEN_SET_CLEARCOLOR';
export const OFFSCREEN_SET_SHADOWTYPE = 'OFFSCREEN_SET_SHADOWTYPE';
export const OFFSCREEN_SET_TONE_MAPPING = 'OFFSCREEN_SET_TONE_MAPPING';
export const OFFSCREEN_SET_FOG = 'OFFSCREEN_SET_FOG';
export const OFFSCREEN_SET_CSM = 'OFFSCREEN_SET_CSM';

export const OFFSCREEN_REMOVE_ELEMENT = 'OFFSCREEN_REMOVE_ELEMENT';

export const OFFSCREEN_ADD_POSTPROCESSING = 'OFFSCREEN_ADD_POSTPROCESSING';
export const OFFSCREEN_ADD_PARTICLES = 'OFFSCREEN_ADD_PARTICLES';
export const OFFSCREEN_ADD_ELEMENT = 'OFFSCREEN_ADD_ELEMENT';