export const CONTROLS = {
    ORBIT: "CONTROLS:ORBIT",
    TRANSFORM: "CONTROLS:TRANSFORM",
    FPS: "CONTROLS:FPS",
    FLY: "CONTROLS:FLY",
    TPS: "CONTROLS:TPS",
};

export const AVAILABLE_CONTROLS = Object.keys(CONTROLS);
